### ISSUE TITLE
Bump max Coq version?

### ISSUE THREAD

**Issue by haselwarter** [coq-community/autosubst#31]
According to the `.opam` file, the 1.7 release of Autosubst only supports Coq < 8.16 or dev. Can the max version requirement be bumped?

**Comment by RalfJung** [comment]
Yeah it definitely works with 8.16 and 8.17. Can you prepare a PR? :)

**Comment by haselwarter** [comment]
What happens now that https://github.com/coq-community/autosubst/pull/32 is merged? Could a new tag (v1.8) be created? Who prepares the PR for the v1.8 opam file against coq/opam-coq-archive ?

**Comment by haselwarter** [comment]
@palmskog tagged v1.8 and published the release to opam. Thanks Ralf and Karl!
