### ISSUE TITLE
New release for Coq V8.19.1?

### ISSUE THREAD

**Issue by jeandudey** [coq-community/autosubst#34]
Currently in GNU Guix [autosubst is packaged](https://packages.guix.gnu.org/packages/coq-autosubst/1.8/) and we are in the process of migrating to Coq V8.19.1 and latest tag of autosusbt doesn't compile, so we opted to use https://github.com/coq-community/autosubst/commit/6ba0acccef68c75f6cca8928706c726754d69791 commit as a patch but would be great if a new release was tagged.

**Comment by palmskog** [comment]
@jeandudey there is now https://github.com/coq-community/autosubst/releases/tag/v1.9 which is packaged with metadata on the Coq opam archive [here](https://github.com/coq/opam/blob/master/released/packages/coq-autosubst/coq-autosubst.1.9/opam).

**Comment by jeandudey** [comment]
Thanks!

**Comment by palmskog** [comment]
@jeandudey note that we always recommend packagers of Coq and its ecosystem to look at the [Coq Platform](https://github.com/coq/platform/), which is the official distribution of Coq together with libraries and plugins and tools. Every release picks certain versions of packages that are known to work together (and in fact is the main trigger of new package releases/tags). Autosubst is [set to join](https://github.com/coq/platform/issues/351) the Platform for the release with Coq 8.20.0.

**Comment by MSoegtropIMC** [comment]
@jeandudey : to give some specific pointers:

the package pick source files are here:

https://github.com/coq/platform/tree/main/package_picks

there are also tables (The PackageTableXYZ files) here:

https://github.com/coq/platform/tree/main/doc

Picking package versions which work well together is non trivial and it probably would save you time to reuse the picks we do and also likely be more useful to users.

**Comment by jeandudey** [comment]
Thanks for that! In theory Guix has updaters to update packages automagically and could use that information to keep packages in synchronization.
